server.port=8081

spring.application.name=product-service

spring.cloud.nacos.config.server-addr=localhost:8848

management.endpoints.web.exposure.include=health,info
# 显示健康检查的详细信息（比如数据库、Redis 等组件的状态）
management.endpoint.health.show-details=always
spring.cloud.nacos.discovery.metadata.version=v1.0
spring.cloud.nacos.discovery.metadata.env=dev
spring.cloud.nacos.discovery.metadata.region=chengdu
# ========== 链路追踪配置 ==========
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0
# ========== 拉取 Nacos 配置（核心） ==========
spring.config.import=nacos:common-db.properties?group=DEFAULT_GROUP
logging.level.com.alibaba.nacos.client.config=WARN