name: Deploy Backend

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload jar to Server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: |
            ./seckill-user-service/target/*.jar
            ./seckill-product-service/target/*.jar
            ./seckill-order-service/target/*.jar
            ./seckill-gateway/target/*.jar
          target: /root/
          

      - name: Restart Services via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            ps -ef | grep -E "user-service|product-service|order-service|gateway" | grep -v grep | awk '{print $2}' | xargs kill -9 || true
            cd /root
            nohup java -jar seckill-user-service-0.0.1-SNAPSHOT.jar > user.log 2>&1 &
            nohup java -jar seckill-product-service-0.0.1-SNAPSHOT.jar > product.log 2>&1 &
            nohup java -jar seckill-order-service-0.0.1-SNAPSHOT.jar > order.log 2>&1 &
            nohup java -jar seckill-gateway-0.0.1-SNAPSHOT.jar > gateway.log 2>&1 &
